// Fully Automatic Frontend Plugin Loader
// Auto-discovers plugin pages by attempting to import them

import React from 'react';

// Plugin registry - populated automatically
const pluginRegistry = {};

// List of known plugins - this could be generated by a build script
const KNOWN_PLUGINS = [
  'calculator',
  'nodecheck',
  'reportgenerator'
];

// Auto-discover plugin pages by attempting imports
export const discoverPluginPages = () => {
  const pluginPages = {};
  
  KNOWN_PLUGINS.forEach(pluginName => {
    try {
      // Attempt to dynamically import the plugin page
      const PluginPage = React.lazy(() => 
        import(`./${pluginName}/${pluginName.charAt(0).toUpperCase() + pluginName.slice(1)}Page`)
          .catch(() => {
            // If import fails, return a fallback component
            return {
              default: () => (
                <div style={{ padding: '20px' }}>
                  <h1>Plugin Not Found</h1>
                  <p>The {pluginName} plugin could not be loaded.</p>
                </div>
              )
            };
          })
      );
      
      pluginPages[pluginName] = {
        component: PluginPage,
        path: pluginName,
        name: pluginName.charAt(0).toUpperCase() + pluginName.slice(1),
        icon: getPluginIcon(pluginName) // Optional icon
      };
    } catch (error) {
      console.warn(`Failed to load ${pluginName} plugin:`, error);
    }
  });
  
  return pluginPages;
};

// Get plugin icon based on plugin name (optional)
const getPluginIcon = (pluginName) => {
  const iconMap = {
    calculator: '🧮',
    // Add more icons here if needed
    // Set to null for plugins without icons
    // default: null  // No icon by default
  };
  return iconMap[pluginName] || null; // Return null if no icon is defined
};

// Get plugin pages for routing
export const getPluginPages = () => {
  return discoverPluginPages();
};

// Get plugin sidebar items
export const getPluginSidebarItems = () => {
  const pages = discoverPluginPages();
  return Object.values(pages).map(plugin => ({
    path: plugin.path,
    name: plugin.name,
    icon: plugin.icon
  }));
};
