// Auto-generated API functions for kibana plugin
// Generated by refresh_frontend_apis.py
// Do not edit this file manually - it will be overwritten

const API_URL = window._env_?.REACT_APP_API_URL || "http://localhost:8000";

/**
 * Kibana Plugin API Functions
 * Auto-generated from backend implementation
 */

/**
 * GET /
 */
export const kibanaInfo = async () => {
  try {
    const url = `${API_URL}/kibana/`
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling kibanaInfo:', error);
    throw error;
  }
};

/**
 * GET /url
 */
export const getKibanaUrl = async () => {
  try {
    const url = `${API_URL}/kibana/url`
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling getKibanaUrl:', error);
    throw error;
  }
};


// Default export with all functions
export default {
kibanaInfo, getKibanaUrl
};
